In [23]:
## Lets import numpy
import numpy as np


In [24]:
my_lst = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(my_lst)

In [25]:
print("Array: ", arr)

Array:  [ 1  2  3  4  5  6  7  8  9 10]


In [26]:
type(arr)

numpy.ndarray

In [27]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [3,4,5,6,7]
my_lst4 = [4,5,6,7,8]
my_lst5 = [5,6,7,8,9]

arr1=np.array([my_lst1,my_lst2,my_lst3,my_lst4,my_lst5])

In [28]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
type(arr)

numpy.ndarray

In [30]:
arr.shape

(10,)

Indexing 


In [31]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[4]

5

In [33]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [34]:
arr1[1:,:2]

array([[2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

In [35]:
arr1[:,2:]

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])